#!/usr/bin/env php
<?php

require_once __DIR__.'/../../vendor/autoload.php';

const MAX_USERS = 500;
const MAX_TAGS = 15;
const MAX_LIKES = 20;

const LOCALE = "fr_FR";

$f = Faker\Factory::create();
$file = '';

function generateImage ($gender) {
    $images = [
        1 => [
            '../fixtures/male1.jpg',
            '../fixtures/male2.jpg',
            '../fixtures/male3.jpg',
            '../fixtures/male4.jpg',
            '../fixtures/male5.jpg',
            '../fixtures/male6.jpg',
            '../fixtures/male7.jpg',
            '../fixtures/male8.jpg',
            '../fixtures/male9.jpg',
            '../fixtures/male10.jpg',

        ],
        2 => [
            '../fixtures/female1.jpg',
            '../fixtures/female2.jpg',
            '../fixtures/female3.jpg',
            '../fixtures/female4.jpg',
            '../fixtures/female5.jpg',
            '../fixtures/female6.jpg',
            '../fixtures/female7.jpg',
            '../fixtures/female8.jpg',
            '../fixtures/female9.jpg',
            '../fixtures/female10.jpg',
        ]
    ];

    return $images[$gender][rand(0,9)];
}

function generateUser($i, $f) {
    $first_name = $f->firstName;
    $last_name = $f->lastName;
    $username = str_replace('.', '',$f->userName);
    $email = $f->email;
    $password = password_hash($f->password(), PASSWORD_DEFAULT);
    $birthdate = ($f->dateTimeBetween('-70 years', '-18 years'))->format('Y-m-d H:i:s');
    $gender = rand(1,2);
    $orientation = rand(1,3);
    $bio = $f->paragraph;
    $country = substr($f->country, 0, 30);
    $state = '';
    $city = substr($f->city, 0,25);
    $zip = substr($f->postcode, 0, 25);
    $score = rand(0,100);
    $token = md5(microtime(false));
    $token_date = $f->date("Y-m-d H:i:s");
    $active = rand(0,1);
    $register = ($active === 0) ? 0 : rand(0,1);
    $created_at = $f->date("Y-m-d H:i:s");
    $updated_at = $f->date("Y-m-d H:i:s");

    $file = [null,null,null,null,null];
    $maxImage = rand(1,5);
    for($j=0; $j < $maxImage; $j++) {
        $file[$j] = generateImage($gender);
    }

    $sql = 'INSERT INTO user (id, first_name, last_name, username, email, password, birthdate, gender, orientation, bio, country, state, city, zip, file_1, file_2, file_3, file_4, file_5, score, token, token_date, active, register, created_at, updated_at) VALUES ("'.$i.'","'.$first_name.'","'.$last_name.'","'.$username.'","'.$email.'","'.$password.'","'.$birthdate.'","'.$gender.'","'.$orientation.'","'.$bio.'","'.$country.'","'.$state.'","'.$city. '","'.$zip.'","'.$file[0].'","'.$file[1].'","'.$file[2].'","'.$file[3].'","'.$file[4].'","'.$score.'","'.$token.'","'.$token_date.'","'.$active.'","'.$register.'","'.$created_at.'","'.$updated_at.'");';

    return $sql;
}

function generateTags($id) {
    $maxTags = rand(1, MAX_TAGS);
    $ret = '';
    for($i=1; $i <= $maxTags; $i++) {
        $tagId = rand(1,50);
        $sql = 'INSERT INTO user_tag (user_id, tag_id) VALUES ("'.$id.'","'.$tagId.'");';
        $ret .= $sql.PHP_EOL;
    }

    return $ret;
}

function generateConnected($id, $f) {

    $sql = 'INSERT INTO connected (user_id, connect_date) VALUES ("'.$id.'","'.($f->dateTimeBetween('-1 year', 'now'))->format('Y-m-d H:i:s').'");';

    return $sql;
}

function generateLikes($id, $f) {
    $maxLikes = rand(1, MAX_LIKES);
    $ret = '';
    for($i=1;$i <= $maxLikes; $i++) {
        $likerId = rand(1,500);
        $sql = 'INSERT INTO likes (like_id, liked_id, like_date) VALUES ("'.$likerId.'","'.$id.'","'.($f->dateTimeBetween('-1 year', 'now'))->format('Y-m-d H:i:s').'");';
        $ret .= $sql.PHP_EOL;
    }
    $maxView = rand($maxLikes, MAX_LIKES * 4);
    for($i; $i <= $maxView; $i++) {
        $viewerId = rand(1, 500);
        $sql = 'INSERT INTO views (viewer_id, viewed_id, view_date) VALUES ("'.$viewerId.'","'.$id.'","'.($f->dateTimeBetween('-1 year', 'now'))->format('Y-m-d H:i:s').'");';
        $ret .= $sql.PHP_EOL;
    }

    return  $ret;
}

for ($i=1; $i <= MAX_USERS; $i++) {
    $file .= generateUser($i, $f).PHP_EOL.generateTags($i).PHP_EOL.generateConnected($i, $f).PHP_EOL.generateLikes($i, $f).PHP_EOL.PHP_EOL;
}

echo $file;